name: Auto update .NET frameworks json

on:
  push:
    branches:
      - main
  schedule:
    - cron:  '0 8 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK 5.0.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
      - run: dotnet new console
      - run: dotnet add package NuGet.Frameworks
      - run: |
          echo '
            using System;
            using NuGet.Frameworks;
            using System.Text.Json;

            namespace app
            {
              class Program
              {
                static void Main(string[] args)
                {
                  var obj = new DefaultFrameworkMappings();
                  string jsonString = JsonSerializer.Serialize(obj);
                  Console.WriteLine(jsonString);
                }
              }
            }
          ' > Program.cs
      - run: dotnet build
      - run: dotnet run > frameworks.json
      - name: Create commits
        run: |
          git config user.name 'Admon Sasson'
          git config user.email 'admon.sasson@snyk.io'
          git add frameworks.json
          git commit -m "chore: New version of frameworks.json"
      - name: Open production pull request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: 'master'
          destination_branch: 'master'
          pr_title: 'Release develop into master'
          pr_body: 'Production release 🛠'
          pr_label: 'auto-pr'
          github_token: ${{ secrets.GITHUB_TOKEN }}
